game:
  name: CartPole-v1
model:
  dropout: 0.0
  in_size: 4
  out_size: 2
  policy_net_layers:
  - 64
  - 32
  value_net_layers:
  - 64
  - 32
  models_path: best_models\ppo_cart_pole.kpt
rollout:
  calc_batch_size: 512
  discount_factor: 0.99
  gae_lambda: 0.95
  max_buffer_size: 2048
  observation_size: 4
training:
  batch_size: 64
  grad_norm: 1.0
  lr: 3e-4
  n_epochs: 10
  output_folder: ../gym_output/cart_pole
  ppo:
    clip_range: 0.2
    entropy_coef: 0.0
    normalize_advantage: true
    value_function_coef: 0.5
  save:
    model_name: cart_pole
    n_last_steps: 10
    save_every_n_step: 5
    target_metric: reward
    target_op: '>'
